### ISSUE TITLE
Simple question

### ISSUE THREAD

**Issue by sepiropht** [iorust/resp#3]
Maybe my question is stupid, but i tried to use your crate, and i just want to understand why decoder only take a `BufReader`,
why not a simple string for example ? Performance reason ? 
In my use case i have string like this, that i want to parse "*2\r\n$4\r\nECHO\r\n$3\r\nhey\r\n".

**Comment by pymongo** [comment]
use these code to parse a simple string

```
fn main() {
    use std::io::BufReader;
    use resp::Decoder;
    let input = b"*2\r\n$4\r\nECHO\r\n$3\r\nhey\r\n";
    let mut decoder = Decoder::new(BufReader::new(input.as_slice()));
    dbg!(decoder.decode().unwrap());
}
```
